version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - MONGODB_URI=${MONGODB_URI}
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend 